### ISSUE TITLE
JQuery like API?

### ISSUE THREAD

**Issue by dhruvbird** [lloyd/JSONSelect#8]
Hello,
  This isn't as much of an issue as a feature, but was wondering if it makes sense provide a jQuery like API which:
- Allowes chaining
- Clings on to the jQuery object if available

So that (in the browser), one can do stuff like:

var names = JSONSelect("string.name", OBJECT).map(jQuery.trim).map(function(name) {
  return "The name is: " + name;
});

names.toArray() returns the real array, but names would be a jQuery-like object.

**Comment by lloyd** [comment]
For reference (this isn't documented anywhere yet), the current API includes three functions:
- `.match(string selector, object matchTarget)` - match a selector against an object and return an array of results
- `.forEach(string selector, object matchTarget, function cb)` - same as match, but rather than returning an array your callback will be invoked for each match
- `.compile(string selector)` - compile a string selector into an object that holds the selector in a parsed form and has `.match` and `.forEach` members

So my thought is the api is pretty simple already, and the `forEach` and `compile` functions would let you make very idiomatic jquery bindings if you wanted.  

`.map()`, for instance, is part of JavaScript 1.6, so when writing code in node or for extensions, there's no utility in built-in higher level abstractions.  Point is, it seems like for the most part you're suggesting building in features that belong at a higher level.

Feel free to come back at me with a patch if I'm being stupid.

**Comment by dhruvbird** [comment]
Hello,
  I think jsonselect is super and that a more idiomatic interface would be nice!! For example, see https://gist.github.com/987196

In the example, you can call _add()_ to add more elements to result set and do all sorts of operations (which you can also do on arrays) and chain the whole thing together. We could also add stuff like _unique()_ that doesn't exist on normal the js Array object.

Do let me know if something looks funny/doesn't make sense.
